### ISSUE TITLE
runs on non decimals

### ISSUE THREAD

**Issue by stoplion** [bendrucker/decimal-to-percent#1]
decimalToPercent(10)
//equates to 1000%

**Comment by bendrucker** [comment]
The readme is very clear that there's no range limitations: https://github.com/bendrucker/decimal-to-percent#topercentdecimal---string

There's a test against that behavior: https://github.com/bendrucker/decimal-to-percent/blob/master/test.js#L21

https://en.wikipedia.org/wiki/Decimal

> A decimal numeral, or just decimal, or, improperly decimal number, refers generally to the notation of a number in the decimal system, which contains a decimal separator (for example 10.00 or 3.14159). Sometimes these terms are used for any numeral in the decimal system. A decimal may also refer to any digit after the decimal separator, such as in "3.14 is the approximation of π to two decimals".

`10.0` is assuredly a decimal in the most common context and therefore `10` is as well.

**Comment by stoplion** [comment]
Then why not add to the README?
```
decimalToPercent(10)
equates to 1000%
```
